---
title: "Papers with preprints"
author: "Karthik Ram & Jennifer Lin"
date: "7/6/2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo = FALSE, warning=FALSE}
suppressPackageStartupMessages(library(tidyverse, warn.conflicts = FALSE, quietly = TRUE))
suppressPackageStartupMessages(library(rcrossref))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(glue))
suppressPackageStartupMessages(library(janitor))
suppressPackageStartupMessages(library(httr))
```


```{r}

get_names <- function(x) {
  z <- glue("http://api.crossref.org/journals/", x) %>% httr::GET()
  if (httr::status_code(z) == 200) {
    zz <- jsonlite::fromJSON(content(z, as = "text"))
    data.frame(issn = x, publisher = zz$message$publisher, title = zz$message$title, stringsAsFactors = FALSE)
  } else {
    "NULL"
  }
}

```

```{r get_facets, cache = TRUE}
url <- "https://api.crossref.org/works?filter=relation.type:has-preprint&facet=issn:*"
y <- httr::GET(url) %>% httr::content()
df <-  (y$message$facets$issn$values) %>% bind_rows() %>% t() %>% data.frame()
df_clean <- df %>% rownames_to_column("issn")
names(df_clean) <- c("issn", "count")

df_clean %>%  mutate(issn2 = str_replace(issn, "http://id.crossref.org/issn/", "")) %>% 
  select(issn2, count) -> df2
names(df2) <- c("issn", "count")
```

```{r get_issns, cache = TRUE, message = FALSE}
stuff <- list()
for (i in 1:nrow(df2)) {
  x = df2[i, ]$issn
  res <- get_names(x)
  message("Retrieving issn ", i)
  stuff[[i]] <- res
}

stuff1 <- stuff[-(which(lengths(stuff) == 1))]
issn_lookup <- bind_rows(stuff1)
write_csv(issn_lookup, path = "issn_lookup.csv")
```


```{r merge_issn_data, results= "as-is", cache = TRUE}
results <- left_join(df2, issn_lookup, by = "issn")
res <- results %>% filter(!is.na(publisher) & !is.na(title))
res %>% select(publisher, title, count) %>% distinct(publisher, count, title) -> clean_full_df
knitr::kable(clean_full_df)
```

```{r}
write_csv(clean_full_df, path = "full_preprint_count.csv") 
```




```

